import type { Steps, StepsByFilename } from "$lib/types";
import { addStepsToMarkdown } from "./add-steps-to-markdown";

describe('addStepsToMarkdown', () => {
  test('initial', () => {
    const filename = 'src/routes/+page.svelte';
    const file_start = 'hi';
    const markdown = `# Normal Heading
Explain what we're going to do:

[[${filename}#02]]  

And then

[[${filename}#03]]  

And some more prose.`;
    const steps: Steps = {
      '01': file_start,
      '02': 'hello',
      '03': 'hello world!',
    };
    const stepsByFilename: StepsByFilename = {
      [filename]: steps
    };
    expect(addStepsToMarkdown({ markdown, stepsByFilename })).toMatchInlineSnapshot(`
      {
        "app_changes": {
          "src/routes/+page.svelte": "hello world!",
        },
        "markdown_with_steps": "# Normal Heading
      Explain what we're going to do:

      \`\`\`diff
      hi
      --diff-border--
      hello
      \`\`\`  

      And then

      \`\`\`diff
      hello
      --diff-border--
      hello world!
      \`\`\`  

      And some more prose.",
      }
    `);
  });
});



const goalMarkdownOnceHavingOwnSnapshotExtension = `# Normal Heading
    Explain what we're going to do:
    
    [[+page.svelte.steps#02]]  
    
    And some more prose.
    
    [//begin]: # "Autogenerated link references for markdown compatibility"
    [+page.svelte.steps#02]: app/src/routes/+page.svelte.steps.md "+page.svelte.steps"
    [//end]: # "Autogenerated link references"
    `;