import type { Steps, StepsByFilename } from "$lib/types";
import { addStepsToMarkdown } from "./add-steps-to-markdown";

describe('addStepsToMarkdown', () => {
  test('initial', () => {
    const markdown = `# Normal Heading
Explain what we're going to do:

[[+page.svelte.steps#02]]  

And some more prose.

[//begin]: # "Autogenerated link references for markdown compatibility"
[+page.svelte.steps#02]: app/src/routes/+page.svelte.steps.md "+page.svelte.steps"
[//end]: # "Autogenerated link references"
`;
    const steps: Steps = {
      '01': 'hi',
      '02': 'hello',
      '03': 'hello world!',
    };
    const stepsByFilename: StepsByFilename = {
      'src/routes/+page.svelte': {
        steps
      }
    };
    expect(addStepsToMarkdown({ markdown, stepsByFilename })).toMatchInlineSnapshot(`
      "# Normal Heading
      Explain what we're going to do:

      [[+page.svelte.steps#02]]  

      And some more prose.

      [//begin]: # \\"Autogenerated link references for markdown compatibility\\"
      [+page.svelte.steps#02]: app/src/routes/+page.svelte.steps.md \\"+page.svelte.steps\\"
      [//end]: # \\"Autogenerated link references\\"
      "
    `);
  });
});


